# @package task
defaults:
  - kitchen_state
  - _self_

intent_conditioning: true
intent_dim: 7
intent_emb_dim: 64
intent_type: encoded_mean
intent_predictor: true
intent_horizon: 8
intent_training_mode: joint
