# @package task
# LIBERO-Goal single-task: turn_on_the_stove — image observations
defaults:
  - libero_spatial_image
  - _self_

env_name: "libero_goal"
env_type: "image"

dataset_path: /home/ldahiya/LIBERO/libero/datasets/libero_goal/turn_on_the_stove_demo.hdf5
dataset_paths: null

bddl_file: /home/ldahiya/LIBERO/libero/libero/bddl_files/libero_goal/turn_on_the_stove.bddl
bddl_files: null

num_envs: 5
